name: Deploy 

on:
  deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare yaml 
      run: |
        echo "task - ${{ github.event.deployment.task }}"
        echo "environment - ${{ github.event.deployment.environment }}"
        echo "payload - ${{ toJson(github.event.deployment.payload) }}"
